create database ppt;
show databases;
use ppt;
select FirstName,EmailAddress from adventureworks_customers;
select distinct FirstName from adventureworks_customers;
select * from adventureworks_customers;
select * from adventureworks_customers where CustomerKey=11001;
select EmailAddress from adventureworks_customers where CustomerKey=11001;
select MaritalStatus from adventureworks_customers where FirstName='JON';
select FirstName,LastName,AnnualIncome from adventureworks_customers where AnnualIncome <> '$90000';
select FirstName,LastName,AnnualIncome from adventureworks_customers where FirstName = "JON" AND LastName = "YANG";
select FirstName,LastName,AnnualIncome from adventureworks_customers where FirstName = "JON" AND LastName = "YANG";
select * from adventureworks_products order by ProductPrice DESC;
select * from adventureworks_products limit 2;
select min(ProductPrice) from adventureworks_products;
select avg(ProductPrice) from adventureworks_products;
select * from adventureworks_customers where FirstName lIKE "c%e";
select * from adventureworks_customers where FirstName lIKE "%or%";
select * from adventureworks_customers where FirstName lIKE "_%e";
select * from adventureworks_products;
select * from adventureworks_products where ProductKey IN (214,219);
select * from adventureworks_products where ProductKey IN (214,219);
select * from adventureworks_products where ProductKey BETWEEN 214 AND 219;
select  ProductKey as sudhir from adventureworks_products;
select c.ProductKey, c.ProductName  from adventureworks_products as c;
select c.ProductKey as sudhir, c.ProductName  from adventureworks_products as c;
select c.ProductKey as sudhir, c.ProductName  from adventureworks_products c;
select c.ProductKey sudhir, c.ProductName  from adventureworks_products c;
select count(EducationLevel) total_count from adventureworks_customers group by EducationLevel;
select count(EducationLevel) total_count, EducationLevel from adventureworks_customers group by EducationLevel;
select count(EducationLevel) total_count, EducationLevel from adventureworks_customers group by EducationLevel;
select EducationLevel from adventureworks_customers group by EducationLevel;
select EducationLevel from adventureworks_customers group by EducationLevel;
select * from adventureworks_products group by (ModelName) having (ProductKey)>200;